"""Report outputs: JSON report, PDF documents, EHR session note and referral ticket."""

import os
import json as _json
import datetime as _datetime
import tempfile as _tempfile
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from core.config import AppConfig, PROJECT_ROOT

# Final test metrics saved by the notebook (Section 7.2). Copy the file from the run's
# report_images/ folder into the project's report_images/ folder to show it in the app.
METRICS_CSV_PATH = PROJECT_ROOT / "report_images" / "test_loss_and_metrics.csv"


def load_reported_test_metrics(path=METRICS_CSV_PATH) -> Optional[Dict[str, float]]:
    """Read the final test-set QWK and accuracy saved by the notebook, if the file exists.

    Uses the argmax decision rule, because that is how this app turns probabilities into a
    stage (core/agents.py). Returns None when the file is missing or malformed, so the
    app never shows a number that is not backed by a saved run.
    """
    import csv
    try:
        with open(path, newline="", encoding="utf-8") as handle:
            row = next(csv.DictReader(handle))
        return {
            "qwk": float(row["argmax_qwk"]),
            "accuracy": float(row["argmax_accuracy"]),
        }
    except (OSError, StopIteration, KeyError, ValueError):
        return None


def describe_reported_metrics(metrics: Optional[Dict[str, float]] = None) -> str:
    """One-sentence summary of the saved test metrics, or a neutral sentence if unavailable."""
    metrics = load_reported_test_metrics() if metrics is None else metrics
    if metrics is None:
        return "Test-set QWK and accuracy are reported in the project report."
    return (
        f"On the held-out test set the model reached a QWK of {metrics['qwk']:.3f} "
        f"and accuracy of {metrics['accuracy'] * 100:.1f}% with the argmax decision this app uses "
        "(saved notebook results)."
    )


def generate_report_json(stage_name: str, confidence: float, probabilities: dict,
                         advisory_urgency: str, advisory_followup: str,
                         advisory_plan: str, ehr_text: str,
                         research_support: Optional[dict] = None) -> str:
    """Serializes the current diagnosis to a timestamped JSON file for download."""
    if not stage_name or not probabilities or not ehr_text:
        return None
    report = {
        "retinatrace_report": {
            "generated_at": _datetime.datetime.now().isoformat(),
            "model": "EfficientNetB3 + U-Net + CBR (RetinaTrace AI)",
            "diagnosis": {
                "stage_name": stage_name,
                "confidence_pct": round(confidence * 100, 2),
                "probabilities": {k: round(v * 100, 2) for k, v in probabilities.items()},
            },
            "clinical_advisory": {
                "urgency": advisory_urgency,
                "followup": advisory_followup,
                "action_plan": advisory_plan,
            },
            "ehr_note": ehr_text,
            "research_visual_support": research_support or {
                "available": False,
                "message": "No experimental visual-support metrics available.",
            },
            "disclaimer": "This report is generated by an AI assistive tool and must be reviewed by a qualified ophthalmologist before any clinical decision.",
        }
    }
    tmp = _tempfile.NamedTemporaryFile(delete=False, suffix="_retinatrace_report.json", mode="w", encoding="utf-8")
    _json.dump(report, tmp, indent=2)
    tmp.close()
    return tmp.name


def generate_document_pdf(title: str, body: str, images: Optional[List[Tuple[str, Any]]] = None) -> str:
    """Create a clean, printable PDF copy of a generated clinical document."""
    if not body or not str(body).strip():
        return None
    from html import escape as _escape
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Image as ReportLabImage
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    filename = _tempfile.NamedTemporaryFile(delete=False, suffix="_retinatrace.pdf").name
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocumentTitle", parent=styles["Title"], alignment=TA_CENTER,
        fontName="Helvetica-Bold", fontSize=15, leading=19, spaceAfter=5,
    )
    body_style = ParagraphStyle(
        "DocumentBody", parent=styles["BodyText"], fontName="Helvetica",
        fontSize=9.2, leading=13, spaceAfter=3,
    )
    section_style = ParagraphStyle(
        "DocumentSection", parent=body_style, fontName="Helvetica-Bold",
        textColor="#0f766e", spaceBefore=6, spaceAfter=4,
    )
    footer_style = ParagraphStyle(
        "DocumentFooter", parent=styles["BodyText"], fontSize=7.5,
        textColor="#64748b", spaceBefore=10,
    )
    document = SimpleDocTemplate(
        filename, pagesize=A4, rightMargin=18 * mm, leftMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=title, author="RetinaTrace AI",
    )
    story = [Paragraph(_escape(title), title_style), Spacer(1, 4)]
    for line in str(body).splitlines():
        clean_line = line.strip()
        if not clean_line:
            story.append(Spacer(1, 4))
        elif clean_line.startswith("="):
            story.append(Paragraph("<font color='#cbd5e1'>" + _escape(clean_line) + "</font>", body_style))
        elif ":" not in clean_line and clean_line.isupper() and len(clean_line) < 45:
            story.append(Paragraph(_escape(clean_line), section_style))
        elif ":" in clean_line:
            label, value = clean_line.split(":", 1)
            story.append(Paragraph(
                f"<b>{_escape(label.strip())}:</b> {_escape(value.strip())}", body_style
            ))
        else:
            story.append(Paragraph(_escape(clean_line), body_style))
    temporary_images = []
    for label, source in images or []:
        if source is None:
            continue
        try:
            from PIL import Image as PILImage
            image_array = np.asarray(source)
            if image_array.dtype != np.uint8:
                image_array = np.clip(image_array * (255.0 if image_array.max() <= 1.0 else 1.0), 0, 255).astype(np.uint8)
            if image_array.ndim == 2:
                image_array = np.repeat(image_array[:, :, None], 3, axis=2)
            image_path = _tempfile.NamedTemporaryFile(delete=False, suffix="_retinatrace_visual.png").name
            PILImage.fromarray(image_array[:, :, :3]).save(image_path)
            temporary_images.append(image_path)
            image = PILImage.open(image_path)
            image_width = 170 * mm
            image_height = min(85 * mm, image_width * image.height / max(image.width, 1))
            story.extend([
                Spacer(1, 8),
                Paragraph(_escape(label), section_style),
                ReportLabImage(image_path, width=image_width, height=image_height),
            ])
        except (TypeError, ValueError, OSError):
            continue
    story.append(Paragraph(
        "Generated by RetinaTrace AI. Review with a qualified ophthalmologist before clinical use.",
        footer_style,
    ))
    try:
        document.build(story)
    finally:
        for image_path in temporary_images:
            try:
                os.remove(image_path)
            except OSError:
                pass
    return filename


def generate_full_report_pdf(stage_name: str, confidence: float, probabilities: dict,
                             advisory_urgency: str, advisory_followup: str,
                             advisory_plan: str, ehr_text: str,
                             research_support: Optional[dict] = None,
                             original_image: Any = None, cam_image: Any = None,
                             lesion_image: Any = None, pred_context: Optional[dict] = None) -> str:
    """Create a formatted PDF containing the complete diagnostic report."""
    if not stage_name or not probabilities or not ehr_text:
        return None
    from app.patient import patient_header_text
    probability_lines = "\n".join(
        f"{label}: {value * 100:.2f}%" for label, value in probabilities.items()
    )
    visual_support = research_support or {}
    visual_lines = (
        f"Available: {visual_support.get('available', False)}\n"
        f"Attention/lesion overlap: {visual_support.get('attention_lesion_iou', 0.0):.3f}\n"
        f"Lesion burden: {visual_support.get('lesion_burden_pct', 0.0):.2f}%\n"
        f"Vessel density: {visual_support.get('vessel_density_pct', 0.0):.2f}%\n"
        f"Affected areas: {visual_support.get('affected_quadrants', 0)}/4\n"
        f"Evidence consistency: {visual_support.get('prediction_evidence_consistency', 'Unavailable')}"
    )
    ehr_lines = ehr_text.splitlines()
    ehr_body = "\n".join(ehr_lines[2:]) if len(ehr_lines) > 2 else ehr_text
    report_body = (
        patient_header_text(pred_context) + "\n\n"
        "DIAGNOSIS\n"
        f"Predicted stage: {stage_name}\n"
        f"Model confidence: {confidence * 100:.2f}%\n"
        "\nPROBABILITY BREAKDOWN\n"
        f"{probability_lines}\n"
        "\nCLINICAL ADVISORY\n"
        f"Urgency: {advisory_urgency}\n"
        f"Recommended follow-up: {advisory_followup}\n"
        f"Action plan: {advisory_plan}\n"
        "\nVISUAL SUPPORT\n"
        f"{visual_lines}\n"
        "\nCLINICAL SESSION NOTE\n"
        f"{ehr_body}\n"
        "==========================================================="
    )
    report_images = [
        ("Uploaded fundus image", original_image),
        ("Grad-CAM attention visual", cam_image),
        ("U-Net pseudo-mask demo (not segmentation)", lesion_image),
    ]
    return generate_document_pdf("RetinaTrace Full Diagnostic Report", report_body, report_images)


def build_ehr_note(diag: Dict[str, Any], expl: Dict[str, Any], adv: Dict[str, Any],
                   consistency: Dict[str, Any], overlap: Dict[str, Any],
                   flagged: bool, threshold: float, demo_preset: bool = False,
                   header: str = "", red_flags: Optional[List[str]] = None,
                   outcome: str = "") -> str:
    """Build the exportable clinical session (EHR) note for one analysis.

    When demo_preset is True the note states that the stage and confidence are fixed
    demo values rather than a model prediction.
    """
    stage = diag["stage"]
    clean_quad = expl['quadrant_desc'].replace('**', '').replace('`', '')
    gate_label = outcome or ('OVERRIDE (FLAGGED)' if flagged else 'APPROVED')
    red_flag_line = f"Red-flag symptoms       : {'; '.join(red_flags)}\n" if red_flags else ""
    ehr_text = (
        "RETINATRACE AI | CLINICAL SESSION NOTE\n"
        "===========================================================\n"
        + (header + "\n\n" if header else "")
        + "ASSESSMENT\n"
        f"Predicted DR stage      : Stage {stage} - {diag['stage_name']}\n"
        f"Model confidence        : {diag['confidence']*100:.2f}%\n"
        f"Evidence consistency    : {consistency.get('status', 'INSUFFICIENT EVIDENCE')}\n"
        f"Main retinal area       : {clean_quad}\n"
        "\nSAFETY REVIEW\n"
        f"Governance status       : {gate_label}\n"
        + red_flag_line
        +
        f"Safety threshold        : {threshold*100:.0f}%\n"
        f"Visual support          : IoU {overlap.get('iou', 0.0):.3f} | Vessel density {expl.get('vessel_density', 0.0):.2f}% | Affected areas {expl.get('affected_quadrants_count', 0)}/4\n"
        "\nCARE PLAN\n"
        f"Urgency                : {adv['urgency']}\n"
        f"Recommended follow-up  : {adv['followup']}\n"
        f"Action plan            : {adv['plan']}\n"
        "\nCLINICIAN SIGN-OFF\n"
        "Name: ______________________   Signature: __________________\n"
        "==========================================================="
    )
    if demo_preset:
        ehr_text = ehr_text.replace(
            "ASSESSMENT\n",
            "ASSESSMENT\n"
            "Result source           : DEMO PRESET - fixed illustrative values, not model output\n",
            1,
        )
    return ehr_text


def build_referral_ticket(triage_code: str, facility: str, wait_time: str, stage: int,
                          risk_pct: float, risk_label: str, age: float, diabetes_type: str,
                          hba1c: float, duration_years: float, systolic_bp: float,
                          protocol: str, header: str = "", urgent_note: str = "") -> str:
    """Build the illustrative example referral summary text for the triage simulator."""
    referral_ticket = (
        "RETINATRACE AI | EXAMPLE REFERRAL SUMMARY (ILLUSTRATIVE)\n"
        "===========================================================\n"
        + (header + "\n\n" if header else "")
        + (urgent_note + "\n\n" if urgent_note else "")
        + "ROUTING\n"
        f"Priority                : {triage_code}\n"
        f"Referral facility       : {facility}\n"
        f"Recommended timeframe  : {wait_time}\n"
        f"Image stage             : Stage {stage} ({AppConfig.CLASS_NAMES[stage]})\n"
        f"Estimated 10-year risk : {risk_pct:.1f}% ({risk_label})\n"
        "Risk estimate status    : Illustrative only, not a validated clinical model\n"
        "\nPATIENT DETAILS\n"
        f"Age {age:.0f}y | {diabetes_type} | HbA1c {hba1c:.1f}% | Diabetes duration {duration_years:.0f}y | BP {systolic_bp:.0f} mmHg\n"
        "\nRECOMMENDED ACTION\n"
        f"{protocol}\n"
        "\nCLINICIAN SIGN-OFF\n"
        "Clinician name: _________________   Medical Reg: __________\n"
        "Signature: ______________________   Date: _________________\n"
        "==========================================================="
    )
    return referral_ticket
